name: Refactor workflow for GitHub Pages deployment

on:
  push:
    branches:
      - main
      - CI/CD  # Thêm branch này nếu bạn muốn chạy từ cả 2 branch

permissions:
  contents: write  # Đây là dòng cực kỳ quan trọng để sửa lỗi 403

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Nên nâng cấp lên v4 luôn

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4 # Nên nâng cấp lên v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
