name: Deploy to GitHub Pages

on:
  push:
    branches:
      - CI/CD

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir public
          echo "<h1>Hello CI/CD GitHub</h1>" > public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./BaiTap7/public  # CHÍNH LÀ DÒNG NÀY: Trỏ thẳng vào thư mục public
